language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="68d9fc0d-27ba-4ada-87fe-1e9422ad725a"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -emelyanov.am@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
